stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 src/constants.h
    - cpplint --verbose=0 src/ekf_15_state.h
    - cpplint --verbose=0 src/navigation.h
    - cpplint --verbose=0 src/tilt_compass.h
    - cpplint --verbose=0 src/transforms.h
    - cpplint --verbose=0 src/utils.h
    - cpplint --verbose=0 src/ekf_15_state.cpp
    - cpplint --verbose=0 src/tilt_compass.cpp
    - cpplint --verbose=0 src/transforms.cpp
    - cpplint --verbose=0 src/utils.cpp
  